services:
  - type: web
    name: shasha-web
    env: docker
    repo: https://github.com/russyncb/shasha.git # Your actual repository URL
    branch: main # Or whichever branch you want to deploy
    buildCommand: docker build -t shasha-web .
    # Remove the startCommand as it's causing an error
    envVars:
      - key: DB_HOST
        value: dpg-your-database-host.render.com # You'll need to replace this
      - key: DB_DATABASE
        value: shasha_db
      - key: DB_USERNAME
        value: shasha_user # You'll need to set this
      - key: DB_PASSWORD
        value: your_password # You'll need to set this securely