services:
  - type: web
    name: shasha-web
    env: docker
    repo: https://github.com/russyncb/shasha.git # Replace with your actual repository URL
    branch: main # Or whichever branch you want to deploy
    buildCommand: docker build -t shasha-web .
    startCommand: docker run -p 10000:80 shasha-web
    envVars:
      - key: DB_HOST
        fromService:
          type: pserv
          name: shasha-database
          property: host
      - key: DB_PORT
        fromService:
          type: pserv
          name: shasha-database
          property: port
      - key: DB_DATABASE
        fromService:
          type: pserv
          name: shasha-database
          property: database
      - key: DB_USERNAME
        fromService:
          type: pserv
          name: shasha-database
          property: username
      - key: DB_PASSWORD
        fromService:
          type: pserv
          name: shasha-database
          property: password

  - type: pserv
    name: shasha-database
    env: docker
    plan: free
    disk:
      name: data
      mountPath: /var/lib/mysql
      sizeGB: 1